### ISSUE TITLE
Few questions

### ISSUE THREAD

**Issue by BiscItz** [Exunys/AirHub-V2#4]
Im gonna get straight to the point but i just want to say that im kind of a newbie to exploiting so im sorry if i dont understand much

My first question is what executor should i use now ? i tried the link you gave for electron but it seems down..
Secondly is is this compatible with macos ?
Thirdly is im only here for the autoaim actually so if you have another exploit i could use thats simpler id love to use it
ty !! ^^

**Comment by Exunys** [comment]
Hello, its totally okay if you're confused as of the current state of roblox exploiting has changed for the better. Currently, there are no public exploits because they are all patched. The exploit I used to develop this script (Synapse X) is now out of service permanently and Electron is working to get unpatched. You can hardly find a private exploit which is expensive and unstable with minimal support for crucial functionality.

So to in short, this script at the current state is unusable, you must wait for trusted script execution software to get released and that will eventually happen but we all just need to be patient and make sure its safe to use once it even gets released.

And also, any script supports any platform whether phone or macos or whatever. The script executor needs to support the platform (.exe / .apk / .dmg).
