### ISSUE TITLE
Does this script still work?

### ISSUE THREAD

**Issue by YousufSSyed** [Exunys/AirHub-V2#5]
As of now there are script executors that still work, and can execute scripts like Infinite Yield, when I tried this script in my executor it didn't do anything.

**Comment by yhqe** [comment]
> [YousufSSyed](/YousufSSyed)

as of right now, seems like it doesn't work
might work on krampus but idk

**Comment by Exunys** [comment]
This UI Library is made with a Drawing library, so these are all the dependencies in order for the script to work:

ESP: 
![image](https://github.com/Exunys/AirHub-V2/assets/76539058/40283aa8-9397-458b-9733-9ae51fd33c1e)

Aimbot:
![image](https://github.com/Exunys/AirHub-V2/assets/76539058/5be3e472-63dc-4efe-ac68-1cfe5493190e)

And yes this script works just fine there is no bug or any logical error, your issue is in the nature of an executor / unsupported functions issue which means I can't help you here in any way unless you tell your script developer to add support for these required functions.
