### ISSUE TITLE
instantly breaks if game.players is renamed 💀

### ISSUE THREAD

**Issue by fhudufin** [Exunys/AirHub-V2#9]
use getservice idiots

**Comment by Exunys** [comment]
Hello "idiot", I am the only developer working on this script by the way and I don't appreciate the arrogant introduction. Since you are so confident, please try to point me to a single instance where "game.Players" is used in AirHub V2, even further look for an instance in both the ESP and Aimbot V3 module for me not using "GetService" to index "Players".
